### ISSUE TITLE
How many learning parameters does the pre-trained DimeNet++ model have?

### ISSUE THREAD

**Issue by qikuizhu** [klicperajo/dimenet#16]
How many learning parameters does the pre-trained DimeNet++ model have?
How can I count this?
I would like to compare the number of parameters with other models like SchNet and MEGNet.

**Comment by gasteigerjo** [comment]
You should be able to simply call `dimenet_pp.summary()` to directly get the number of trainable parameters: https://www.tensorflow.org/guide/keras/functional#introduction

**Comment by masashitsubaki** [comment]
To try dimenet_pp.summary(), I run train.ipynb in your repository by Google colaboratory, but I failed.

<img width="478" alt="image" src="https://user-images.githubusercontent.com/40475654/111907176-7acecc80-8a97-11eb-9b18-18d8aa424d7a.png">

For now, just tell me the total number of parameters in DimeNet++ because my question is "how many learning parameters does the pre-trained DimeNet++ model have?"
