### ISSUE TITLE
GPU training problem

### ISSUE THREAD

**Issue by LingsparkQ** [klicperajo/dimenet#27]
Would you mind if I ask you guys to post something much more concrete about the environment configuration? I came up with some problems when I am trying to train Dimenet++ using GPU. It seems the problem exists because the version of dependencies conflict with each other.

Btw, I am wondering whether the extensive option being True when training hom/lumo/gap is reasonable. It seems that avg aggregation should match the pyhsic's law when facing these 3 properties.

**Comment by gasteigerjo** [comment]
Thank you for reaching out!

I'm not sure what else you would need. I just tested creating an environment and it worked for me:
```
conda create -n dimenet
conda activate dimenet
conda install numpy scipy sympy tensorflow-gpu tqdm nb_conda
pip install tensorflow_addons
```
Then open one of the notebooks and run it. Maybe you are not using Anaconda and that's why dependencies fail for you?

Also, the imports might fail if you do not use the `conda_forge` channel and activate strict channel priority via `conda config --set channel_priority strict`.

I agree that these three are intensive properties and have also trained a model with extensive=False back then. But at least within the limited scope of QM9, extensive=True worked better. This might not hold for datasets with more variety in system sizes.
