### ISSUE TITLE
Reason for the linear weight twice

### ISSUE THREAD

**Issue by Nokimann** [klicperajo/dimenet#31]
Thank you for your work.

I found in DimNet++ and GemNet that the basis functions are linearly weighted twice in the model rather than just once.

Do you have any reason for it because the multiplication of two matrices can be represented as just one matrix?

I checked the dimension reduction in-between two matrix multiplications. This could reduce the number of parameters, but are there other reasons?

**Comment by gasteigerjo** [comment]
The small bottleneck dimension between layers results in a function that generalizes better than a single layer would, i.e. doing this reduces the model error. The reduced number of parameters is just a side-effect.

This is nothing new. Researchers have repeatedly found that multiple linear layers, while in principle reducible to a single layer, often in fact perform better due to improved training dynamics.
